---
name: Checks

on:
  pull_request:
    branches:
      - 'master'
      - 'api-shop'
      - 'ari'

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run actions/checkout@v2
        uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose up
